universe = vanilla
executable = testing.py 


+Group = "GRAD"
+Project = "AI_ROBOTICS"
+ProjectDescription = "simulating the RoboCup Rescue Simulator"


log = /u/animesh9/Desktop/MultiAgentDRL-RCRS/rcrs-server-master/boot/condor/log/log.$(Process)
error = /u/animesh9/Desktop/MultiAgentDRL-RCRS/rcrs-server-master/boot/condor/error/err.$(Process)
output = /u/animesh9/Desktop/MultiAgentDRL-RCRS/rcrs-server-master/boot/condor/output/out.$(Process)

notify_user = animesh.goyal9@gmail.com
notification = error
request_memory = 4000

should_transfer_files = YES
when_to_transfer_output = ON_Exit
transfer_output         = True
transfer_input_files    = /u/animesh9/Desktop/Environment, testing.py

arguments = "PPO2 200 200 2 2 0.0025 64"
queue 1


log = /u/animesh9/Desktop/MultiAgentDRL-RCRS/rcrs-server-master/boot/condor/log/log.$(Process)
error = /u/animesh9/Desktop/MultiAgentDRL-RCRS/rcrs-server-master/boot/condor/error/err.$(Process)
output = /u/animesh9/Desktop/MultiAgentDRL-RCRS/rcrs-server-master/boot/condor/output/out.$(Process)

arguments = "PPO2 200 200 2 2 0.0075 64"
queue 1
